import uuid

from fastapi import APIRouter, Depends

from research_orchestrator.api.deps import get_evaluation_service
from research_orchestrator.api.schemas import ErrorResponse, EvaluationRequest, EvaluationResponse
from research_orchestrator.services.evaluation_service import EvaluationService

router = APIRouter(prefix="/v1/evaluations", tags=["evaluations"])


@router.post(
    "/report",
    response_model=list[EvaluationResponse],
    summary="Evaluate a report payload",
    description=(
        "Evaluates a report payload using built-in metrics: hallucination resistance, "
        "citation accuracy, and report quality. Pass the `structured_output` from a "
        "ReportResponse to evaluate."
    ),
    response_description="List of evaluation metric results.",
    responses={
        401: {"model": ErrorResponse, "description": "Missing or invalid API key"},
        422: {"model": ErrorResponse, "description": "Invalid report payload"},
    },
)
async def evaluate_report_payload(
    payload: EvaluationRequest,
    service: EvaluationService = Depends(get_evaluation_service),
) -> list[EvaluationResponse]:
    results = await service.evaluate_report_payload(payload.report)
    return [EvaluationResponse(**item) for item in results]


@router.post(
    "/runs/{run_id}",
    response_model=list[EvaluationResponse],
    summary="Evaluate a completed run",
    description=(
        "Evaluates the report generated by a completed research run. "
        "The run must have a generated report."
    ),
    response_description="List of evaluation metric results.",
    responses={
        401: {"model": ErrorResponse, "description": "Missing or invalid API key"},
        404: {"model": ErrorResponse, "description": "Run or report not found"},
    },
)
async def evaluate_run(
    run_id: uuid.UUID,
    service: EvaluationService = Depends(get_evaluation_service),
) -> list[EvaluationResponse]:
    results = await service.evaluate_run(run_id)
    return [EvaluationResponse(**item) for item in results]

